### ISSUE TITLE
 torch._six has been removed

### ISSUE THREAD

**Issue by zahrakhanjani128** [asvspoof-challenge/2021#21]
Torch does not seem to support torch._six anymore and it has been removed.
Refer - https://github.com/pytorch/pytorch/pull/94709

Asvspoof 2021 baseline model still has dependency on it.

(I am trying the baseline below: https://github.com/asvspoof-challenge/2021/blob/main/DF/Baseline-LFCC-LCNN/project/baseline_DF/02_eval_alternative.sh

#Script to quickly evaluate a evaluation set in DF task)

I get this error:
ModuleNotFoundError: No module named 'torch._six'

I tried:
 from torch import inf
nothing changed!
How should I fix it?

**Comment by TonyWangX** [comment]
Hi @zahrakhanjani128 

Because the code was developed based on Pytorch version 1.6.0, it still depends on torch._six.

See required dependency:
https://github.com/asvspoof-challenge/2021/tree/main/DF/Baseline-LFCC-LCNN#requirement

The script will try to load the specified conda environment https://github.com/asvspoof-challenge/2021/blob/aae41bb3f4f38795ebf6901c7bbf3461e4ad662b/DF/Baseline-LFCC-LCNN/project/baseline_DF/02_eval_alternative.sh#L40

If it loads your own conda environment, the Pytorch version may be different, then the above error comes out.

**Comment by zahrakhanjani128** [comment]
Many thanks for your quick responses! Downgraded Pytorch worked well.
